Escuela/Models/ErrorViewModel.cs
using System;

namespace Escuela.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Escuela/Controllers/CourseController.cs
using Escuela.Dominio;
using Escuela.Servicio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class CourseController : Controller
    {
        private readonly ILogger<CourseController> _logger;
        private ICourese icourse;

        public CourseController(ILogger<CourseController> logger, ICourese icourse)
        {
            this.icourse = icourse;
            _logger = logger;
        }

        public IActionResult insert(Course c)
        {

            return View();
        }

        public IActionResult Indexdos(Course c)
        {
            if (ModelState.IsValid)
            {
                icourse.Insertar(c);
                return View();
            }
            else
            {
                return View("Indexdos", c);
            }
            
        }

        public IActionResult GetAll()
        {
            var DandoFormatoJson = icourse.ListarCursos();

            return Json(new { data = DandoFormatoJson });
        }


        public IActionResult MostrarCourses()
        {
            return View();
        }
    }
}

Escuela/Controllers/EnrollementController.cs
using Escuela.Dominio;
using Escuela.Models;
using Escuela.Servicio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;


namespace Escuela.Controllers
{
    public class EnrollementController : Controller
    {
        private readonly ILogger<EnrollementController> _logger;
        private ICourese icourse;
        private IEnrollements ienrollements;
        private IStudent istudent;

        public EnrollementController(ILogger<EnrollementController> logger, ICourese icourse, IEnrollements ienrollements, IStudent istudent)
        {
            this.icourse = icourse;
            this.ienrollements = ienrollements;
            this.istudent = istudent;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

      

        public IActionResult ComboBox()
        {
            var informationofthecombo = icourse.ListarCursos();
            var informationofthecomboforStudents = istudent.ListOfStudents();


            List<SelectListItem> listOfCourse = new List<SelectListItem>();
            List<SelectListItem> listStudent = new List<SelectListItem>();


            foreach (var iterarinformation in informationofthecombo)
            {
                listOfCourse.Add(
                    new SelectListItem
                    {
                        Text = iterarinformation.Title,
                        Value = Convert.ToString(iterarinformation.CourseId)
                    }

                    );
                ViewBag.estadolistcourse = listOfCourse;
            }

            foreach (var iterarinformation in informationofthecomboforStudents)
            {
                listStudent.Add(
                    new SelectListItem
                    {
                        Text = iterarinformation.FirstMidName,
                        Value = Convert.ToString(iterarinformation.StudentId)
                    }

                    );
                ViewBag.estadoliststudent = listStudent;
            }


            return View();
        }

        public IActionResult GetinformationCombobox(Enrollment e)
        {
            _ = e;
            Console.WriteLine(e.CourseID);
            return View("comboBox");
        }

       
        public IActionResult ListaEnrollement()
        {

            var listado = ienrollements.UnionDeTablas();
            _ = listado;


            return View(listado);
        }

        public IActionResult Insertar()
        {

            return View();
        }

       
        
    }
}

Escuela/Controllers/HomeController.cs
using Escuela.Dominio;
using Escuela.Models;
using Escuela.Servicio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ICourese icourse;
        private IEnrollements ienrollements;
        private IStudent istudent;
        public HomeController(ILogger<HomeController> logger, ICourese icourse, IEnrollements ienrollements, IStudent istudent)
        {
            this.icourse = icourse;
            this.ienrollements = ienrollements;
            this.istudent = istudent;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult GetAllForJoinJsonLinq()
        {
            var listado = ienrollements.UnionDeTablas();
            var CombinacionDeArreglos = (from union in listado
                                         select new
                                         {
                                             union.Course.Title,
                                             union.Student.LastName,
                                             union.Student.FirstMidName,
                                             union.Grade
                                         }).ToList();

            return Json(new { CombinacionDeArreglos});
        }

        public IActionResult GetAll()
        {
            var DandoFormatoJson = icourse.ListarCursos();

            return Json(new { data = DandoFormatoJson });
        }

        public IActionResult Privacy()
        {
            
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

Escuela/Controllers/StudentController.cs
using Escuela.Dominio;
using Escuela.Models;
using Escuela.Servicio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class StudentController : Controller
    {
        private readonly ILogger<StudentController> _logger;
        private IStudent istudent;

        public StudentController(ILogger<StudentController> logger, IStudent istudent)
        {
            this.istudent = istudent;
            _logger = logger;
        }


        public IActionResult Insertar()
        {

            return View();
        }

        public IActionResult SaveStudent(Students s)
        {
            if (ModelState.IsValid)
            {
                istudent.Save(s);
                return View();
            }
            else
            {
                return View("SaveStudent", s);
            }

        }

        public IActionResult GetAllStudent()
        {
            var DandoFormatoJsonStudent = istudent.ListOfStudents();

            return Json(new { data = DandoFormatoJsonStudent });
        }

        public IActionResult MostrarAlumnos()
        {
            return View();
        }

    }
}

Escuela/Views/Course/Indexdos.cshtml
@model Escuela.Dominio.Course
@{ ViewData["Title"] = "Indexdos";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<script src="https://kit.fontawesome.com/16bd784e77.js" crossorigin="anonymous"></script>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js">


@using (Html.BeginForm("Indexdos", "Course", FormMethod.Post))
{


<h2 class=" animate__animated animate__bounce"> Registre un curso</h2>
                <br />
                                <h3 class="text-center"> BIENVENIDO</h3>
                                                <br>
                                                                <i class="fas fa-book"></i>
                                                                                <label>Title</label>
                                                                                                <br />
                                                                                                                @Html.TextBoxFor(m => m.Title)
                                                                                                                                <br />
                                                                                                                                                @Html.ValidationMessageFor(m => m.Title)
                                                                                                                                                                <br />
                                                                                                                                                                                <br />
                                                                                                                                                                                                <i class="far fa-star"></i>
                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                <label>Credits</label>
                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                @Html.TextBoxFor(m => m.Credits)
                                                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                                                @Html.ValidationMessageFor(m => m.Credits)
                                                                                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                                                                                                <input type="submit" class="btn btn-success animate__animated animate__backInDown" value="GUARDAR" />
                                                                                                                                                                                                                                                                                                                                                                <br>
    <br />
                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("Lista de Courses", "MostrarCourses", "Course")</button>
<br />
<br />
}



<script src="https://cdn.boomcdn.com/libs/wow-js/1.3.0/wow.js"></script>
<script type="text/javascript">
    new WOW().init();
</script>

Escuela/Views/Course/MostrarCourses.cshtml
@{ ViewData["Title"] = "MostrarCourses";
                Layout = "~/Views/Shared/_Layout.cshtml"; }


<h1>Lista de Cursos</h1>
<br />
<button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("Registrar Nuevo Curso", "Indexdos", "Course")</button>
<br />
<br />
<table id="mitabla" class="table table-dark table-hover">
    <thead>
        <tr>
            @*<th>Course Id</th>*@
            <th>Title</th>
            <th>Credits</th>
        </tr>

    </thead>

</table>

@section scripts{

    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script>

        $(document).ready(function () {

            var tabla = $('#mitabla').DataTable({
                "ajax": {
                    "url": '/Course/GetAll',
                    "type": "get",
                    "datatype": "json"
                },
                "columns": [
                    /*{ "data": "courseId", "name": "courserId", "autoWidth": true },*/
                    { "data": "title", "name": "title", "autoWidth": true },
                    { "data": "credits", "name": "credits", "autoWidth": true }

                ]


            })
        })
    </script>

}

<button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("INICIO", "Index", "Home")</button>

Escuela/Views/Enrollement/ComboBox.cshtml
@model Escuela.Dominio.Enrollment


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>comboBox</title>
</head>
<body>

    @using (Html.BeginForm("GetinformationCombobox", "Enrollement", FormMethod.Post))
    {

<h1>ComboBox</h1>
                @Html.DropDownListFor(a => a.CourseID, new SelectList(ViewBag.estadolistcourse, "Value", "Text"), "Select a course", new { @class = "form-control" })
                                <br />
                                                <br />
                                                                @Html.DropDownListFor(a => a.StudentID, new SelectList(ViewBag.estadoliststudent, "Value", "Text"), "Select a Student", new { @class = "form-control" })
                                                                                <br />
                                                                                                <br />

                                                                                                                <input type="submit" class="btn btn-success animate__animated animate__backInDown" />
                                                                                                                                <br />
                                                                                                                                                <br />
                                                                                                                                                                <button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("Lista de Enrollement", "ListaEnrollement","Enrollement")</button>}
</body>
</html>

Escuela/Views/Enrollement/ListaEnrollement.cshtml
@model List<Escuela.Dominio.Enrollment>
@{ ViewData["Title"] = "ListaEnrollement";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1 class="text-center">Lista de Enrollement</h1>
<br />
<button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("Registrar Nuevo Enrollement", "ComboBox", "Enrollement")</button>
<br />
<br />
<table id="mitablaenr" class="table table-dark table-hover">
    <thead>
        <tr>
            @*<th>Id Ernrollment</th>
                <th>Student Id</th>
                <th>Course Id</th>*@
            <th>Last Name</th>
            <th>FirstMidName</th>
            <th>Course</th>
        </tr>

    </thead>

    <tbody>
        @foreach (var iteracion in Model)
        {
<tr>
    @*<td>@iteracion.EnrollmentId</td>
        <td>@iteracion.StudentID</td>
        <td>@iteracion.Course.CourseId</td>*@
    <td>@iteracion.Student.LastName</td>
    <td>@iteracion.Student.FirstMidName</td>
    <td>@iteracion.Course.Title</td>
</tr>}


    </tbody>

</table>

@section Scripts{

    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script>

        $(document).ready(function () {

            var tabla = $('#mitablaenr').DataTable({


            })
        })
    </script>
}

<button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("INICIO", "Index", "Home")</button>

Escuela/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home Page"; }


<div class="text-center">
    <h1 class="display-4">BIENVENIDO</h1>

</div>

<link rel="stylesheet" href="~/css/Inicio.css" />

<link rel="stylesheet"
      href="https://kit.fontawesome.com/ffd11ebe0f.js" crossorigin="anonymous" />

<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js>" />

<script src="https://kit.fontawesome.com/ffd11ebe0f.js" crossorigin="anonymous"></script>

<body>
    <header class="bg_animate">
        <div class="header_nav">
            <div class="contenedor">
                <nav>
                    <br />
                    <i class="fas fa-user-circle"></i>
                    @Html.ActionLink("Mostrar Estudiantes", "MostrarAlumnos", "Student")
                    <br />
                    <br />
                    <i class="fa fa-bullhorn"></i>
                    @Html.ActionLink("Lista Enrollement", "ListaEnrollement", "Enrollement")
                    <br />
                    <br />
                    <i class="fa fa-building"></i>
                    @Html.ActionLink("Mostrar Course", "MostrarCourses", "Course")
                    <br />
                    <br />
                </nav>
            </div>
        </div>
        <div class="burbujas">
            <div class="burbuja"></div>
            <div class="burbuja"></div>
            <div class="burbuja"></div>
            <div class="burbuja"></div>
            <div class="burbuja"></div>
            <div class="burbuja"></div>
            <div class="burbuja"></div>
            <div class="burbuja"></div>
            <div class="burbuja"></div>
            <div class="burbuja"></div>
        </div>
    </header>
</body>

Escuela/Views/Student/MostrarAlumnos.cshtml
@{ ViewData["Title"] = "MostrarAlumnos";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1 class="text-center">Mostrar Estudiantes</h1>
<br />
<button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("Registrar Nuevo Estudiante", "SaveStudent", "Student")</button>
<br />
<br />
<table id="mitablastu" class="table table-dark table-hover">
    <thead>
        <tr>
            <th>LastName</th>
            <th>MidName</th>
            <th>Date</th>
            
            
        </tr>

    </thead>

</table>

@section scripts{

    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script>

        $(document).ready(function () {

            var tabla = $('#mitablastu').DataTable({
                "ajax": {
                    "url": '/Student/GetAllStudent',
                    "type": "get",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "lastName", "name": "lastName", "autoWidth": true },
                    { "data": "firstMidName", "name": "firstMidName", "autoWidth": true },
                    { "data": "enrollmentsDate", "name": "enrollmentsDate", "autoWidth": true }
                   

                ]


            })
        })
    </script>

    
}

<button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("INICIO", "Index","Home")</button>

Escuela/Views/Student/SaveStudent.cshtml
@model Escuela.Dominio.Students
@{ ViewData["Title"] = "SaveStudent";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h3 class="wow animate__animated animate__pulse" data-wow-duration="2s" data-wow-delay="2s">Inscripcion de Estudiantes</h3>
<script src="https://cdn.boomcdn.com/libs/wow-js/1.3.0/wow.js"></script>
<script type="text/javascript">new WOW().init();</script>

<link rel="stylesheet"
      href="https://kit.fontawesome.com/ffd11ebe0f.js" crossorigin="anonymous" />

<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js>" />

<script src="https://kit.fontawesome.com/ffd11ebe0f.js" crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/16bd784e77.js" crossorigin="anonymous"></script>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js">


@using (Html.BeginForm("SaveStudent", "Student", FormMethod.Post))
{


<h4 class="text-center">BIENVENIDO</h4>
                <br>
                                <i class="fa fa-file-signature"></i>
                                                <label>First Mid Name</label>
                                                                <br />
                                                                                @Html.TextBoxFor(m => m.FirstMidName)
                                                                                                <br />
                                                                                                                @Html.ValidationMessageFor(m => m.FirstMidName)
                                                                                                                                <br />
                                                                                                                                                <br />
                                                                                                                                                                <i class="fa fa-input-text"></i>
                                                                                                                                                                                <br />
                                                                                                                                                                                                <label>LastName</label>
                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                @Html.TextBoxFor(m => m.LastName)
                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                @Html.ValidationMessageFor(m => m.LastName)
                                                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                                                                <div class="form-group">
                                                                                                                                                                                                                                                                                                                    <i class="fas fa-calendar-day"></i>
                                                                                                                                                                                                                                                                                                                    <label>Date</label>
                                                                                                                                                                                                                                                                                                                    <input required asp-for="EnrollmentsDate" class="form-control " />
                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                <input type="submit" class="btn btn-success animate__animated animate__backInDown" value="GUARDAR" />
                                                                                                                                                                                                                                                                                                                                                <br>
    <br />
    
                                                                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn btn-info animate_animated animate_backInDown"> @Html.ActionLink("Lista de Estudiantes Registrados", "MostrarAlumnos")</button>
                                                                                                                                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                                                                                                                <br />
                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                
}